#**반복가능객체의 형변환**

* list(반복가능객체)
 > 함수 사용 결과가 괄호 안에 있는 반복 가능
 객체가 리스트로 변환된 결과

* tuple(반복가능객체)
 > 함수 사용 결과가 괄호 안에 있는 반복 가능
 객체가 tuple로 변환된 결과

* set(반복 가능 객체)
 > 함수 사용 결과가 괄호 안에 있는 반복가능객체가 set로 변환된 결과

In [ ]:
list('안녕하세요')
tuple([10,20,20,30])
set([10, 10, 10, 20, 30])

{10, 20, 30}

In [ ]:
# 소괄호가 생략된 튜플임
# 튜플 언패킹(튜플을 풀어버리면서이 일어나면서 각각의 변수에는 각각의 값이 대입되게 된다.

a, b = '박준', 30

print(f'이름은 {a}, 나이는 {b}살')

이름은 박준, 나이는 30살

In [ ]:
# 리스트 언패킹이 일어나면서 각각의 값이 각각의 변수에 순서대로 사용 할 수 있다.

name, age, height = ['박준', 30, 183]
                     
print(f'이름 : {name}, 나이 : {age}, 키 : {height}')

이름 : 박준, 나이 : 30, 키 : 183

#**5. 세트**

* 중복된 값을 저장 할 수 없다.
* 순서가 없다(인덱스 번호 쓸 수 없다.)
* 수정 가능(mutable)

##**5-1. 세트 생성**

1. set() 함수 사용
2. 중괄호{} 사용

In [ ]:
s1 = {'바나나', '사과', '오렌지', '바나나'}

type(s1) # type은 각 대표 타이틀로 생각하면 된다.
print(s1) # 순서가 존재하지 않고, 중복된 값을 저장하지 않는다.

# s1[1]

# 비어있는 세트를 만들때는 반드시 set() 함수를 사용해야 한다.
# dict = 딕셔너리 타입을 얘기한다.

s2 = {}
type(s2)
print(s2)

{'바나나', '오렌지', '사과'}
{}

##**5-2. 세트 관련 메소드**

In [ ]:
names = set()

# alt + shift + 위 아래 화살표 --> 코드 복사 붙여넣기
# alt + 위 아래 화살표 --> 코드 이동

# 요소 추가
# add (요소) 괄호 안에 있는 요소를 세트에 추가한다.
names.add('박준')
names.add('김치')
names.add('배추')

print(names)

# () 소괄호 안에 쓴 것은 인자
# pop을 쓸 때는 뭐가 삭제가 될 지 모른다.
# pop() : 세트 속 요소 한 개 삭제, 함수 사용 결과가 삭제된 요소 값(return)

print(names.pop())
print(names)

# remove(요소) : 세트 속에서 요소 삭제

names.remove('박준')
print(names)

# discard(요소) : 세트 속에서 요소 삭제, 없는 요소라면 오류 안남

names.discard('햄버거')
print(names)

{'김치', '박준', '배추'}
김치
{'박준', '배추'}
{'배추'}
{'배추'}

#**6. 딕셔너리**

* key와 value 한쌍(item)으로 저장하는 방법
* key (인덱스 대산 사용)는 중복 X, value는 중복 O
* 인덱스 번호는 사용하지 않는다.
* 수정 가능하다(matable)

##**6-1. 딕셔너리 생성**

1. dict()함수 사용
2. {} 사용

In [ ]:
di1 = {'국어' : 50, '영어' : 70, '수학' : 80}

print(di1)


# 요소의 갯수
# len(반복가능객체)

len(di1) # 3 요소의 갯수 3개
di1['국어'] # 인덱스 번호 대신에 key 값 사용

# 있는 key는 수정
di1['국어'] = 80
print(di1) # di1 국어 타이틀에 80 값으로 수정

# 없는 key는 추가
di1['과학'] = 100
print(di1)

{'국어': 50, '영어': 70, '수학': 80}
{'국어': 80, '영어': 70, '수학': 80}
{'국어': 80, '영어': 70, '수학': 80, '과학': 100}

##**6-2. 딕셔너리 관련 메소드**

In [ ]:
scores = {'국어' : 50, '수학' : 70, '영어' : 80}

# scores['국어'] 번째 방의 값을 알려주라는 뜻
# get(key) : 해당 key에 저장된 값이 함수 사용 결과가 된다, 없는 key 사용해도 오류 안남

scores.get('국어')

# pop(key) : 해당 key를 삭제, 함수 사용 결과는 삭제된 value 값
scores.pop('국어')
print(scores)

# popitem() : 딕셔너리의 마지막 요소를 삭제, 함수 사용 결과는 key와 value 한쌍이 들어있는 tuple type 이다.
# print(type(scores.popitem())) # 영어랑 80이 삭제가 됌

k, v = scores.popitem()
print(scores)

print(f'k:{k}, v:{v}')

scores['과학'] = 100
scores['사회'] = 20

print(scores)

# keys() 함수 사용 결과는 딕셔너리의 key 값들이 들어있는 반복가능객체(dict_keys 타입)
list(scores.keys())

# values() 함수 사용 결과는 딕셔너리의 value 값들이 들어있는 반복가능객체(dict_values 타입)
scores.values()

# items() : 함수 사용 결과는 딕셔너리의 key와 value(item)이 한쌍으로 묶여있는 튜플들이 요소로
#           들어있는 반복 가능 객체(dict_items 타입)
list(scores.items())

{'수학': 70, '영어': 80}
{'수학': 70}
k:영어, v:80
{'수학': 70, '과학': 100, '사회': 20}

[('수학', 70), ('과학', 100), ('사회', 20)]

##**6-3. 복잡한 딕셔너리**

* 치환, 치환, 치환 하여 해석하자, 결과가 무슨 타입인지가 중요하다

In [ ]:
dictionary = {'id' : 'abc123',
              'pw' : '0105',
              'scores' : [50, 89, 64],
              'info' : {'name' : '박준', 
                        'major' : '게임', 
                        'age' : 50}
              }

# 해당 dictinary 안에는 학생에 대한 정보가 들어있다.
# 학생 이름과 학과, 나이를 출력하고
print(dictionary['info']['name'])
print(dictionary.get('info').get('major'))
print(dictionary['info'].get('age'))

# 나이를 20살로 수정한 뒤에
dictionary['info']['age'] = 20

# 다시 출력하기
print(dictionary)

박준
게임
50
{'id': 'abc123', 'pw': '0105', 'scores': [50, 89, 64], 'info': {'name': '박준', 'major': '게임', 'age': 20}}

##**7. in / not in 연산자와 반복가능객체**

* 요소 in 반복가능객체
> 요소가 반복가능객체 안에 포함되어 있다면 True 아니면 False

* 요소 not in 반복가능객체
> 요소가 반복가능객체 안에 포함되어 있지 않다면 True 아니면 False

In [1]:
'ap' in 'apple' # True
'ap' not in 'apple' # False

10 in [1, 5, 10, 32] # True
[5, 10] not in [1, 5, 10, 32] # True

10 in (1, 5, 6) # False
10 not in (1, 5, 6) # True

s1 = {'박준', '주니', '주뉘'}
'박준' in s1 # True
'박준' not in s1 # False

# 딕셔너리에서 판단 여부는 key 값이다.
di = {'국어' : 20, '영어' : 70, '수학' : 80}

20 in di # False
'국어' in di # True

# di 딕셔너리 안에 value 값에 20이 포함되어 있다면 True 아니면 False가 나오게 작성
num = int(input('입력 >>'))

# di.values() --> [20, 70, 80]
num in di.values()

입력 >>020

True